[build]
  base = "frontend"
  command = "npm run build -- --configuration production"
  publish = "frontend/dist/ticket-management-frontend/browser"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200